language: ruby
# bundler_args: --without development

services:
  # - mongodb
  # - redis-server

matrix:
  allow_failures:
    - rvm: ruby-head

rvm:
  - 2.0.0

before_script:
  # - mongo ruby_china_test --eval 'db.addUser("travis", "test");'
  #- cp config/config.yml.default config/config.yml

# script: RAILS_ENV=test bundle exec rake spec spec:javascript
script: bundle exec rake spec
